- scripts/escape_mission.lua
- scripts/idle.lua
- scripts/missions/ea_hostage.lua
- scripts/modinit.lua
- scripts/prefabs/shared/hostage_1.lua
* `mm_fixnopatrolfacing` fixes a stationary guard placed with the `nopatrol` trait.
* `mm_nopatrolchange` causes a guard to ignore patrol changes (DLC extended campaign alarm level, exec terminals escalation, etc) if a script needs the guard to stick around until alerted. This can also be reasonably applied to patrolling guards.
> Generic behavior traits for the EA Hostage captain.

- scripts/escape_mission.lua
- scripts/modinit.lua
I forgot that `mm_fixnopatrolfacing` was only meant for `nopatrol` units. Make it so that this at least doesn't crash.
> Small fixes for assassination mission

- prefabs_xml/settings.xml
The 1st commit should exactly match the `settings.xml` from the spyface.rar in the Modding Resources pinned post.
Look at the 2nd commit to see the changes.
I have prefabs from Tactical Lamp View, Worldgen Extended, Neptune Corporation, OMNI Foundry Plus, and Mods Combo by Shirsh when I searched for discrepancies, with Shirsh's combo disagreeing with the other mods. (I believe I checked every prop that had impass without cover from the settings.xml)
---
Having this committed in the repo should also help ensure spyface exports performed by separate people are consistent.
---
The modified settings.xml works in spyface on my machine and exporting the prefabs looks correct. I didn't commit those exports just yet, because it would merge-conflict with prefab changes in my other branch.
> Add spyface settings to repo and fix 4 lamps that have cover in other mods

- scripts/modinit.lua
- scripts/serverdefs.lua
- scripts/strings.lua
* Add an option for Distress Call and Tech Expo, so that they can be disabled
* Remove the campaign option and serverdefs definitions for landfill and holostudio.
Mostly just so that I could use MoreMissions to limit a run to specific vanilla missions
> Update campaign options to match the currently available missions

- scripts/btree/actions.lua
- scripts/btree/bountytargetbrain.lua
- scripts/btree/conditions.lua
* When panicked and unarmed, the CEO will react to distractions by fleeing (instead of trying to investigate, as he would when armed)
* Perform the loot-and-arm code before the peek when he first reaches the safe. This behaves better if his peek is interrupted by finding something.
Note: The animations don't play correctly in the latter case. The looting animation stops partway through and the peek animation never plays. Sim behavior is correct.
> Assassination brain tweaks

- .github/workflows/build.yml
I wrote a github action that will automatically download the Example API mod from the steam workshop and use it in conjunction with the provided Makefile in the repository to build a working mod zip. 
Potential things to improve:
- Add caching to the KWAD Builder download so the builder itself and its intermediate cache can be saved between builds
- Host the KWAD builder download somewhere else so the steam workshop download isn't needed.
> Add CI for automatically building the mod

- scripts/modinit.lua
Situations fail to be created if every valid location already has a situation.
As per bug report on Discord (<https://discord.com/channels/313015356052471828/589089660064628736/840587130388480010>)
> fix crash if situation cannot be created

- scripts/missions/mole_insertion.lua
Added delay between a guard seeing the mole and them becoming a witness, so that you can safely shock trap guards with the mole on the other side of the door.
> Fix for Shock Trap/witness interaction

- Makefile
- scripts/missions/weapons_expo.lua
Because reversing guaranteed-Authority for Confusion is funny, but probably not intended.
Also include `modinfo.txt` in both install paths. Mostly just for my own sanity.
> Don't let Tech Expo authority reverse

- scripts/missions/assassination.lua
- scripts/modinit.lua
Covers a variety of situations to make the "Heat Signature Detected" label in the Assassination mission smoother. Still not perfect, but should be close enough to the base game.
> Heat Signature tab fix

- scripts/missions/ai_terminal.lua
remnant of the AI Terminal port, replacement string was already present but the reference still pointed to WORLDEXTEND
> fixed a hanging Worldgen Extended string reference

- scripts/modinit.lua
Fixes #86 
> If there weren't any nearby locations, the `if newSituation` condition wasn't met, so the failover code wasn't running. Moved the failover out of that block, and have it reattempt the old createNewSituation with the widened parameters.
> If there are no valid spawns within the current corp, still attempt to give 3 missions, from any corp at this point.
>
> The same tags array is used in all 3 generated locations, so each of the failover checks (and an extra call to the underlying createNewSituation) will occur at most once per reward screen.
Also tested that this correctly grants no new missions if there's already 2 of each mission on the map (disabled distress call in campaign options for this, because it auto-clears). As expected, the extra failover checks only resulted in …
> Courier Reward: Fix distance failover, and add a followup corp failover

- scripts/abilities/hostage_rescuable_2.lua
- scripts/missions/ea_hostage.lua
* Instead of removing _all_ hooks (something that should only be done at mission end), remove specifically the hooks that are waiting for the courier. Required some cleanup and reordering.
* Releasing the courier without distracting the captain now immediately puts him into overwatch, instead of delaying until the next player action. If you're already under overwatch, the act of releasing the courier is NOT itself a trigger for being shot.
> Fix courier death wiping out side mission hooks / Fix releasing hostage in watched

- scripts/escape_mission.lua
- scripts/strings.lua
* add a Tab line to the opportunity target when first seen
* Pause before Central lines, to avoid being accidentally cleared by Talkative Agents (I think?)
* Don't clear the primary mission's HUD Instructions if present.
> Tweak personnel hijack UI

- scripts/appended_functions/engine_lateInit.lua
- scripts/appended_functions/units_lateInit.lua
- scripts/missions/assassination.lua
* 2 undefined references to `assassination_mission` in appends
* Add an additional trigger for despawning the "hologram" unit.
* Previously, there was a brief window where it looked like the player could steal from both the hologram and the revealed decoy. Now the decoy despawns before returning to player control.
> Assassination fixes

- scripts/appended_functions/serverdefs.lua
- scripts/missions/distress_call.lua
- scripts/modinit.lua
- scripts/propdefs.lua
Previous mean value: 520
Updated mean value: 640
Range is still 300-1000
* Removed single-use items and items <500cr (except TAG pistol and buster chip II, which are usually perceived as higher value)
* Upgrade cloak I to cloak II (other items are Tier II)
* Upgrade Corporate Intel (valuable loot) from 300cr to 500cr. It's too thematic to cut, so I buffed its value.
`800* + 80* + 500 + ~640 = 2020` is just shy of Assassination's current `1500* + 200* + 150* + 300 = 2150` and comparable to a full vault. Unclear whether or not this is reasonable.
If you get a high-roll item that you want to use _and_ make use of the vault card, this is easily the most valuable mission reward.
> Rebalance non-agent Distress Call loot table

- scripts/appended_functions/mission_scoring.lua
- scripts/escape_mission.lua
- scripts/missions/ai_terminal.lua
- scripts/modinit.lua
Replaces the handling used for AI Terminal and Drone Rescue side mission (looks like a bigger change than it is, because I needed to reorder things to define the `updateAgency` callback function before the script hook that uses it)
> Use a callback pattern for generic "update agency" mission rewards

- scripts/missions/ai_terminal.lua
This check is unnecessary as the check for slot cap has already been done one block up. It also prevents you from getting unlimited slots in Endless even after the menu let you pick that option.
> fix program cap on Endless

- scripts/missions/ai_terminal.lua
It's distracting and also gives away the location of the room.
> remove camera pan event on console use

- scripts/missions/assassination.lua
Includes the commit from #187, one additional fix (the real target had a stale planned path that took it outside the safe room on the first turn only), and re-enables the feature.
> Bring back everyone's favorite holographic executive

- scripts/appended_functions/simstore_load.lua
- scripts/escape_mission.lua
- scripts/modinit.lua
- scripts/propdefs.lua
- scripts/tech_expo_itemdefs.lua
Fixes #188
Using custom store types allows us to request a custom amount of given item types, so the mission script has been simplified. We don't need to generate multiple large-nanofabs-worth of items in order to fill the luxury nanofab.
!!! This change removes the code for enforcing no duplicate items in the resultant list. Instead, a `noDupes` flag is added to the traits, without any current implementation to use it.
I'm hoping wodzu will be willing to support a `noDupes` flag as part of `simstore.createStoreItems`, so that the luxury nanofab can be populated without the extra work to enforce no dupes _after_ generating a bunch of items. If not, then this should PR should be amended to put the remove-dupes logic back. (request: …
> Use custom store types for Luxury Nanofab instead of the vanilla mission's "large" value

- scripts/abilities/MM_scrubcameradb.lua
- scripts/abilities/MM_transformer_terminal_10PWR.lua
- scripts/abilities/MM_transformer_terminal_5PWR.lua
- scripts/abilities/MM_workshop_place_item.lua
Found when applying the rubiks bugfix to a bunch of DLC device abilities, and thought to check over here
> Check playerOwner instead of firewalls for device canUse (rubiks bugfix)

- scripts/abilities/MM_petDrone.lua
- scripts/abilities/MM_renameDrone.lua
Fixes #184 
`proxy = true` already enables the ability when an agent is within 2 tiles by taxicab distance. `acquireTargets` is unnecessary, and the `canUnitReach` check can be the final result of `canUseAbility`.
> Disallow diagonal drone interaction

- scripts/missions/ea_hostage.lua
The `no_escape` flag had lain there stealthily until someone was unlucky enough to try and escape without even having seen the courier, let alone freed him.
> Permit escaping from Courier Hostage missions without the Courier

- Makefile
- scripts/abilities/MM_petDrone.lua
- scripts/abilities/MM_renameDrone.lua
- scripts/agentdefs.lua
- scripts/appended_functions/simquery.lua
- scripts/strings.lua
* Hide "BLOCKED" pet drone ability icon when on the other side of a wall. Retain the "OUT OF RANGE" icon state when within 2 tiles and "BLOCKED" when on the other side of a door. These will help players discover that they _can_ pet their drone friends.
* Hide rename drone ability icon when blocked or out of range. Pet drone is enough for discoverability. No need for two icons.
* Prevent drone friend from attempting to path through lethal lasers.
* Add "Uses cover, but is NOT considered friendly by guards" to the REPROGRAMMED tooltip line. These seem to be the main questions from new players of the mod.
Fixes #200 
Fixes #213 
* Don't spawn with the overwatch trait set to true. (It's cleared on movement and has no effect besides.) This becomes visible and confusing with new/upcoming UITR …
> Assorted Refit Drone Friend fixes
